version: '3'

services:
  wireguard-server:
    container_name: wireguard-server
    build: .
    privileged: true
    restart: always
    tty: true
    sysctls:
      - 'net.ipv4.ip_forward=1'
    ports:
      - "5180:80"
      - '51820:51820/udp'
    volumes:
      - './etc/www:/www'
      - './etc/lighttpd/:/etc/lighttpd'
      - './etc/wireguard:/etc/wireguard'
