#!/bin/sh
. /www/functions/utils.sh

########################################################################
########################################################################
########################################################################

POST_STRING=$(cat)
inSign=$(echo $POST_STRING | jq -r '.sign')
mySign=$(_generatesign $POST_STRING)


if [ "$inSign" != "$mySign" ];then
    echo -e '{"ret":0,"msg":"token error","data":{}}'
else
    name=$(echo $POST_STRING | jq -r '.name')
    echo -e $(wireguard_user_add $name)
fi